pages:
  stage: deploy
  script:
    - mkdir .public
    - echo "/theoldfashion/index.html /theoldfashion/theOldFashion.html 301" > ./.public/_redirect
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
