pages:
  stage: deploy
  script:
    - mkdir .public
    - cp theOldFashion.html .public/index.html
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
