pages:
  stage: deploy
  script:
    - mkdir .public
    - echo "/index.html /theOldFashion.html 301" > ./.public/_redirects
    - touch ./public/index.html
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
